### PR TITLE
remove default alg

### PR DESCRIPTION
**Pull request by oscardssmith**
This now exists in OrdinaryDiffEq.jl

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can we add the equivalent tests to https://github.com/SciML/OrdinaryDiffEq.jl/tree/master/lib/OrdinaryDiffEqDefault/test ?

**Comment by oscardssmith** [comment]
will do. Those tests are currently in https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/interface/default_solver_tests.jl but they should be moved.

**Comment by ChrisRackauckas** [comment]
Tests fail here. Also, bump the minor.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by prbzrg** [comment]
I think, this also needs to have higher compat for `OrdinaryDiffEq`.

**Pull request merged**
